import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export const store = new Vuex.Store({

	// Defs:
	state: {
		scrollLock: false,
		// UI
		// If soft keyboard visible on mobile
		softKeyboard: false,
		// Date info
		dates: {
			fullCurrentYear: new Date().getFullYear(),
			months: ["October", "November", "December", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October " ],
			FYMonth: 0,
		},
		// Activities
		activities: [
			{
			  ref: "1",
			  showHighLevel: "Yes",
			  title: "Strategy Development Meeting",
			  subtitle: "For FYFY-1 Accomplishments, FYFY-0 and FYFY+1 Planning, & Out-Year Visioning",
			  fy: 0,
			  monthStart: 0,
			  monthDuration: 1,
			  type: "Internal Executive Meeting",
			  accountable: "Director",
			  role: "Mission Area Associate Directors",
			  involved: "Director<br/>Deputy Director <br/>Mission Area Associate Directors<br/>Regional Directors",
			  description: "Executive level meeting to review successes and challenges of past fiscal year, discuss how Bureau Guidance will be executed for the current fiscal year, as well as strategy development and revisions for out-years and near-term visioning.",
			  inputText: "Accomplishments of each Mission Area from the fiscal year just completed.<br/>Operational Plan for the fiscal year just starting -- includes annual work plans at centers and programs plans in Mission Areas<br/>Opportunities for science planning and capacity building that may inform updates to the Facing Tomorrow's Challenges vision document.<br/>DOI Strategic Plan/Annual Performance Plan measures and Secretarial Milestones",
			  resultsText: "Accomplishments are used in the Greenbook, Annual Financial Report, Annual Performance Report and informational briefings.<br/>Potential adjustments to current fiscal year's operating plan are identified.<br/>Facing Tomorrow’s Challenges provides context for science planning describing the vision for capacity building, high-level priorities for the bureau, both cross-mission and within missions that span a multi-year timeframe.",
			  isUsedFor: "2 -AFR, APR, Greenbook, President's Budget preparation<br/>2a - OMB Briefings<br/>7  - Tactical Planning Meeting<br/>10  - development of Bureau Guidance"
			},
			{
			  ref: "1a",
			  showHighLevel: "",
			  title: "Adjusted allocation guidance within USGS when budget bill is enacted",
			  subtitle: "For FYFY-0",
			  fy: 0,
			  monthStart: 0,
			  monthDuration: 6,
			  type: "Other",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration<br/>Associate Director for Office of Administration<br/>Mission Area Associate Directors",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators<br/>Cost Centers",
			  description: "Bill language is reviewed.  Adjusted guidance is issued if necessary.  Warrant is received, funding is entered into systems, control tables are distributed, and allocation memo and timeline for allocation to the center level begins.",
			  inputText: "Final Bill and Report<br/>Warrants<br/>Apportionments",
			  resultsText: "Availability Controls Set; Funding passed down to the cost center level from the Mission Area level",
			  isUsedFor: "Budget Execution"
			},
			{
			  ref: "2",
			  showHighLevel: "Yes",
			  title: "President’s Budget Prepared and Submitted",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 0,
			  monthDuration: 6,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "The Greenbook is the official budget justification sent to Congress from the Administration.<br/>Settlement is a milestone in this step that occurs in December",
			  inputText: "Description of each Mission Area and Program,<br/>FY-1 accomplishments,<br/>Projected accomplishments in current FY,<br/>Projected accomplishments in FY+1 with the total requested funding and background information,<br/>Funding changes from the previous fiscal year,<br/>Program Changes - describe the impact of an increase or a decrease in funding from the current appropriations including new initiatives,<br/>Reviews from USGS management, DOI management, and OMB",
			  resultsText: "",
			  isUsedFor: "3 - President's Budget Released<br/>7 - Tactical Planning Meeting<br/>4 - Congressional Hearings<br/>14 - House and Senate Mark-Ups<br/>1A - Bill is Enacted"
			},
			{
			  ref: "3",
			  showHighLevel: "",
			  title: "Release of President’s Budget",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 4,
			  monthDuration: 1,
			  type: "Other",
			  accountable: "",
			  role: "",
			  involved: "",
			  description: "The President’s Budget represents the priorities of the USGS, DOI and the Administration.",
			  inputText: "",
			  resultsText: "",
			  isUsedFor: ""
			},
			{
			  ref: "4",
			  showHighLevel: "",
			  title: "Congressional Hearings - Appropriations and Budget",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 4,
			  monthDuration: 4,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration<br/>Associate Director for Office of Communication and Publishing",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "USGS and DOI may have Budget Hearings with Appropriations and other Committees after the President’s Budget Request is submitted and reviewed by Congress.",
			  inputText: "Knowledge of the President's Budget Request and the programs",
			  resultsText: "",
			  isUsedFor: "14 - House and Senate Mark-ups"
			},
			{
			  ref: "5",
			  showHighLevel: "Yes",
			  title: "Synthesis of information from national level partners and stakeholders and from USGS Programs and Program Councils",
			  subtitle: "For FYFY-0",
			  fy: 1,
			  monthStart: 3,
			  monthDuration: 3,
			  type: "Information Synthesis",
			  accountable: "Mission Area Associate Directors",
			  role: "Mission Area Associate Directors<br/>Program Coordinators",
			  involved: "Mission Area Associate Directors<br/>Program Coordinators<br/>Center Directors<br/>Members of councils and similar mechanisms",
			  description: "Represents the mechanisms and processes used to gather information from internal and external partners and stakeholders, Programs, and bureau-level working groups and communities of practice on priorities and science direction",
			  inputText: "Departmental and Administration Priorities,  DOI Strategic Plan, Federal, and other partner priorities synthesized through Mission Area-level processes, Program Councils, and other mechanisms to collaboratively develop program direction, including input from USGS stakeholders, Council of Program Coordinators, Innovation Working Group, and Council of Senior Science Advisors",
			  resultsText: "Long-term and annual science direction determined within Mission Area<br/>Program and Mission Area priorities identified within Mission Area",
			  isUsedFor: "7 - Tactical Planning Mtg<br/>10 - Bureau Guidance<br/>11 - Mission Area Guidance"
			},
			{
			  ref: "6",
			  showHighLevel: "Yes",
			  title: "Synthesis of information from field level partners and stakeholders and from within USGS Science Centers",
			  subtitle: "For FYFY-0",
			  fy: 1,
			  monthStart: 3,
			  monthDuration: 3,
			  type: "Information Synthesis",
			  accountable: "Regional Directors",
			  role: "Regional Directors",
			  involved: "Regional Directors<br/>Center Directors<br/>Center Employees",
			  description: "Represents the mechanisms and processes used to gather information from field, internal and external partners and stakeholders on needs and opportunities, and science centers on capabilities, capacity, and opportunities.",
			  inputText: "Information from regional partnerships and activities, Center Reviews, and synthesized center portfolio analyses",
			  resultsText: "Long-term and annual science direction determined within Mission Area<br/>Program and Mission Area priorities identified within Mission Area",
			  isUsedFor: "7 - Tactical Planning Mtg<br/>10 - Bureau Guidance<br/>11 - Mission Area Guidance"
			},
			{
			  ref: "7",
			  showHighLevel: "Yes",
			  title: "Tactical Planning Meeting",
			  subtitle: "FYFY-0 Status & FYFY+1 Planning",
			  fy: 1,
			  monthStart: 6,
			  monthDuration: 1,
			  type: "Internal Executive Meeting",
			  accountable: "Director",
			  role: "Mission Area Associate Directors",
			  involved: "Director<br/>Deputy Director <br/>Mission Area Associate Directors<br/>Regional Directors",
			  description: "Structured discussions to deliberate on a wide array of field- and mission-based documents and perspectives to be synthesized into a set of bureau-wide opportunities for the coming year and beyond.",
			  inputText: "President’s Budget, DOI Strategic Plan, Perspectives from national stakeholders, Council of Program Coordinators, Council of Senior Science Advisors, Innovation Working Group, Program plans, OMB and DOI budget guidance, Congressional report language, Integrated science investments and opportunities, Information from center reviews, Regional stakeholder meetings",
			  resultsText: "Building blocks are identified for drafting Director's Annual Bureau Guidance.",
			  isUsedFor: "10 - Bureau Guidance<br/>11 - Mission Area Guidance"
			},
			{
			  ref: "8",
			  showHighLevel: "",
			  title: "Link DOI Strategic Plan with USGS Science Strategy Facing Tomorrow's Challenges",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 6,
			  monthDuration: 1,
			  type: "Planning and Performance",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "Ensure that the USGS strategic science plan is in alignment with the DOI Strategic Plan",
			  inputText: "DOI Strategic Plan",
			  resultsText: "USGS Strategic Science Plan",
			  isUsedFor: "13 - Complete DOI Plan Linkage"
			},
			{
			  ref: "9",
			  showHighLevel: "",
			  title: "USGS Budget Formulation",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 6,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "When formulating the DOI submission, BPI must take into account DOI budget guidance, OMB guidance, and OSTP guidance (when available).  During the formulation phases, all budget information is \"close hold\" and shared with only those involved in the actual budget process.  Once budget formally released it is available to all.",
			  inputText: "Annual Strategic Performance Measures and Secretarial Priority Milestones                          Budget Issue Papers",
			  resultsText: "USGS Budget Submission to the Department",
			  isUsedFor: "21 - Budget due to DOI<br/>23 - Prepare OMB Submission"
			},
			{
			  ref: "10",
			  showHighLevel: "Yes",
			  title: "Director's Annual Bureau Guidance",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 7,
			  monthDuration: 1,
			  type: "Policy Document",
			  accountable: "Director",
			  role: "Deputy Director",
			  involved: "Director<br/>Deputy Director <br/>Mission Area Associate Directors<br/>Regional Directors<br/>Associate Director for Budget, Planning, and Integration",
			  description: "Tactical statement of budget directives for the bureau-level activities that USGS intends to undertake in upcoming fiscal year, and is based upon long-term strategies and addresses opportunities and operational priorities.",
			  inputText: "Discussions and deliberations on information and content of the Tactical Planning Meeting",
			  resultsText: "Science priority areas for the next fiscal year<br/>Technology Opportunities for the next fiscal year<br/>Operational Priorities for the next fiscal year",
			  isUsedFor: "11 - Annual Mission Area Guidance"
			},
			{
			  ref: "11",
			  showHighLevel: "Yes",
			  title: "Annual Mission Area Guidance",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 8,
			  monthDuration: 1,
			  type: "Policy Document",
			  accountable: "Mission Area Associate Directors",
			  role: "Mission Area Associate Directors<br/>Program Coordinators",
			  involved: "Mission Area Associate Directors<br/>Program Coordinators<br/>Regional Directors<br/>Center Directors",
			  description: "Mission Area-level budget guidance for upcoming fiscal year, that responds to bureau level guidance, for new and continued activities within Mission Area programmatic line items.",
			  inputText: "DOI Strategic Plan, Bureau-level guidance, Mission Area priorities, Program science direction and priorities (from Program Councils and other mechanisms)",
			  resultsText: "Strategic Guidance for DOI priorities<br/>Director’s Priorities as related to Mission Area<br/>Program-level guidance<br/>Operational Guidance",
			  isUsedFor: "12 - Annual Work Plan Development"
			},
			{
			  ref: "12",
			  showHighLevel: "Yes",
			  title: "Annual Work Plan Development",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 9,
			  monthDuration: 3,
			  type: "Planning and Performance",
			  accountable: "Regional Directors",
			  role: "Center Directors",
			  involved: "Regional Directors<br/>Center Directors<br/>Center Employees",
			  description: "Project, personnel, and account level budget planning in BASIS+ that responds to Mission Area and Program-level guidance for upcoming fiscal year.",
			  inputText: "DOI Strategic Plan, Bureau-level guidance,<br/>Mission Area Annual Guidance with Program-level priorities,<br/>Science capabilities,<br/>Personnel capacity",
			  resultsText: "Projects entered into BASIS+ and reviewed for accuracy.<br/>Annual work plans align with priorities of the Programs that fund the work",
			  isUsedFor: ""
			},
			{
			  ref: "13",
			  showHighLevel: "",
			  title: "Complete DOI Strategic Plan Linkage",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 11,
			  monthDuration: 2,
			  type: "Planning and Performance",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "Ensure that the USGS strategic science plan is in alignment with the DOI Strategic Plan",
			  inputText: "DOI Strategic Plan",
			  resultsText: "Greenbook and Annual Performance Plan and Report",
			  isUsedFor: "9 - FY+2 USGS Budget Guidance"
			},
			{
			  ref: "14",
			  showHighLevel: "",
			  title: "House and Senate Budget Markups",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 7,
			  monthDuration: 5,
			  type: "Formulation",
			  accountable: "Director",
			  role: "External - Congress<br/>Associate Director for Budget Planning and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "During this phase there are many questions coming in from the House/Senate Appropriations Committee staffers.  These questions require a quick turn-around and Budge Planning and Integration works closely with the mission areas and the Director's Office",
			  inputText: "Knowledge of the programs and the President's Budget Request that is being worked on",
			  resultsText: "A House mark and a Senate mark that can move into conference for a final omnibus bill to be issued",
			  isUsedFor: "1A - Adjusted guidance within USGS when Bill is enacted"
			},
			{
			  ref: "15",
			  showHighLevel: "",
			  title: "Develop Communication Campaign Strategy",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 0,
			  monthDuration: 1,
			  type: "Communications",
			  accountable: "Director",
			  role: "Associate Director for Communications and Publishing",
			  involved: "Director<br/>Deputy Director <br/>Mission Area Associate Directors<br/>Regional Directors<br/>Public Affairs Officer<br/>Congressional Liaison Officer",
			  description: "Rules of order process on how messaging is handled by USGS as a whole.<br/>Provides consistent messaging for everyone to use.",
			  inputText: "Bureau Guidance,<br/>DOI Strategic Plan",
			  resultsText: "",
			  isUsedFor: "18- Socialize priority messages"
			},
			{
			  ref: "16",
			  showHighLevel: "",
			  title: "OMB Budget Passback to Agencies, including settlement",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 1,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "External - Office of Management and Budget",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: " A milestone in the President Budget submission process. Decisions are handed down by OMB after their review of the USGS budget submission.  These funding decisions will be the basis for the President’s Budget submission to Congress (Greenbook). OMB passback is \"close hold\" and shared with only those involved in the actual budget process.  Once the budget is formally released it is available to all.",
			  inputText: "",
			  resultsText: "",
			  isUsedFor: "2 - President's Budget Prepared/ Submitted"
			},
			{
			  ref: "17",
			  showHighLevel: "",
			  title: "Develop Budget Initiatives",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 1,
			  monthDuration: 1,
			  type: "Planning and Performance",
			  accountable: "Director",
			  role: "Mission Area Associate Directors",
			  involved: "Mission Area Associate Directors<br/>Regional Directors<br/>Program Coordinators",
			  description: "",
			  inputText: "DOI Strategic Plan,<br/>Priorities identified during visioning and deliberations during the Strategy Development Meeting",
			  resultsText: "",
			  isUsedFor: ""
			},
			{
			  ref: "18",
			  showHighLevel: "",
			  title: "Socialize Priority Messages",
			  subtitle: "",
			  fy: 2,
			  monthStart: 1,
			  monthDuration: 1,
			  type: "Communications",
			  accountable: "",
			  role: "",
			  involved: "",
			  description: "Implementation of communication strategies",
			  inputText: "",
			  resultsText: "",
			  isUsedFor: ""
			},
			{
			  ref: "19",
			  showHighLevel: "",
			  title: "Submit Draft Budget Initiatives",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 3,
			  monthDuration: 2,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Mission Area Associate Directors",
			  involved: "Mission Area Associate Directors<br/>Regional Directors<br/>Program Coordinators",
			  description: "",
			  inputText: "",
			  resultsText: "",
			  isUsedFor: ""
			},
			{
			  ref: "20",
			  showHighLevel: "",
			  title: "Internal USGS Budget Guidance based on priorities",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 5,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration",
			  description: "Guidance to collect USGS initiatives and offsets in preparation for preparing the DOI Submission",
			  inputText: "This is not always issued annually and it is dependent on the Administration, Director, and understanding of the Department's anticipated guidance.",
			  resultsText: "Initial Planning information for USGS leadership to start making preliminary decisions on the Department budget submission.",
			  isUsedFor: "21 - Budget due to DOI"
			},
			{
			  ref: "21",
			  showHighLevel: "",
			  title: "Budget Due to DOI",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 8,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "The Budget due to the Department is based on the guidance we received from the DOI and the decisions made by the Director and Mission Area Associate Directors.",
			  inputText: "Budget Issue Papers<br/>Science Opportunities",
			  resultsText: "DOI passback  based on this submission",
			  isUsedFor: " 22 - DOI Budget Settlement"
			},
			{
			  ref: "22",
			  showHighLevel: "",
			  title: "DOI Budget Passback",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 9,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "Result of DOI review of USGS Budget submission that includes decisions and changes based on Secretarial and Administration priorities.",
			  inputText: "",
			  resultsText: "DOI Budget Settlement on this submission",
			  isUsedFor: "23 - Prepare OMB Submission"
			},
			{
			  ref: "23",
			  showHighLevel: "",
			  title: "Prepare OMB Budget Submission",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 10,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "OMB Submission reflects the DOI settlement decisions.",
			  inputText: "DOI Settlement",
			  resultsText: "OMB Submission",
			  isUsedFor: "24 - Submit to OMB"
			},
			{
			  ref: "24",
			  showHighLevel: "",
			  title: "Submit Budget to OMB",
			  subtitle: "For FYFY+2",
			  fy: 2,
			  monthStart: 11,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "The OMB budget submission includes a budget overview, budget at a glance, Mission area budget chapters, annual performance plan and report, budget issue papers and opportunities.",
			  inputText: "",
			  resultsText: "OMB Settlement",
			  isUsedFor: "2a - OMB Briefings<br/>16 - OMB Budget Passback to Agencies/Settlement"
			},
			{
			  ref: "2a",
			  showHighLevel: "",
			  title: "OMB Budget Briefings",
			  subtitle: "For FYFY+1",
			  fy: 1,
			  monthStart: 0,
			  monthDuration: 1,
			  type: "Formulation",
			  accountable: "Director",
			  role: "Associate Director for Budget, Planning, and Integration",
			  involved: "Director<br/>Deputy Director <br/>Associate Director for Budget, Planning, and Integration<br/>Mission Area Associate Directors<br/>Program Coordinators<br/>Budget Coordinators",
			  description: "Mission Area Associate Directors meet with Office of Management and Budget (OMB) Examiner to brief on the OMB submission.  A presentation is prepared.",
			  inputText: "Knowledge of the OMB submission<br/>Strategy behind decisions",
			  resultsText: "These briefings provide the OMB examiner information about USGS, to work within OMB to determine funding levels.  It becomes the OMB passback.",
			  isUsedFor: "16 - OMB Budget Passback to Agencies/Settlement"
			}
		],
	},
	mutations: {
		scrollLock(state, scrollLock) {
			state.scrollLock = scrollLock
		},
		softKeyboard(state, softKeyboard) {
			state.softKeyboard = softKeyboard
		},
		dates(state, dates) {
			state.dates = dates
		},
		activities(state, activities) {
			state.dates = activities
		},
	},
	getters: {
		scrollLock: state => state.scrollLock,
		softKeyboard: state => state.softKeyboard,
		dates: state => state.dates,
		activities: state => state.activities,
	}
})